from __future__ import annotations

import atexit
import os
from contextlib import contextmanager
from typing import Iterator

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

# One baseline schema rather than the old SQLite migration chain: Postgres is a fresh
# start, so there is no history to replay. Append new entries below; each runs once and
# its index is recorded in schema_migrations.
SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_provider     TEXT    NOT NULL,
    auth_subject      TEXT    NOT NULL,
    handle            TEXT    NOT NULL,
    email             TEXT    NOT NULL DEFAULT '',
    password_hash     TEXT    NOT NULL DEFAULT '',
    display_name      TEXT    NOT NULL DEFAULT '',
    avatar_url        TEXT    NOT NULL DEFAULT '',
    leetcode_username TEXT    NOT NULL DEFAULT '',
    -- Whether your group can see which problems you solved, not just that you did.
    show_problems     BOOLEAN NOT NULL DEFAULT true,
    github_login      TEXT    NOT NULL DEFAULT '',
    github_repo       TEXT    NOT NULL DEFAULT '',
    timezone          TEXT    NOT NULL DEFAULT 'UTC',
    created_at        TEXT    NOT NULL,
    -- auth_provider/auth_subject are vestigial: `identities` is the real record of
    -- how someone signs in, and its primary key already enforces one account per
    -- provider identity. A unique constraint here only fires ahead of the email
    -- index and reports the wrong conflict.
    UNIQUE (handle)
);

-- Case-insensitive and partial: blank means "not set", and several accounts may
-- legitimately have no email or no LeetCode handle.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email
    ON users (lower(email)) WHERE email <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_leetcode
    ON users (lower(leetcode_username)) WHERE leetcode_username <> '';

CREATE TABLE IF NOT EXISTS groups (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT    NOT NULL,
    invite_code TEXT    NOT NULL UNIQUE,
    owner_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- The board's clock. A group needs one shared definition of "today", or
    -- "4 of 5 solved today" means different things to different members.
    timezone    TEXT    NOT NULL DEFAULT 'UTC',
    created_at  TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS memberships (
    group_id  INTEGER NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role      TEXT    NOT NULL DEFAULT 'member',
    joined_at TEXT    NOT NULL,
    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS daily_activity (
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    source  TEXT    NOT NULL,
    day     TEXT    NOT NULL,
    count   INTEGER NOT NULL,
    PRIMARY KEY (user_id, source, day)
);

CREATE INDEX IF NOT EXISTS idx_daily_activity_user_day
    ON daily_activity (user_id, day);

-- One row per way a person can sign in, so an account can have a password *and*
-- Google *and* GitHub without duplicating the user.
CREATE TABLE IF NOT EXISTS identities (
    provider   TEXT    NOT NULL,
    subject    TEXT    NOT NULL,
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TEXT    NOT NULL,
    PRIMARY KEY (provider, subject)
);

CREATE INDEX IF NOT EXISTS idx_identities_user ON identities (user_id);

-- Short-lived email verification codes. One live code per address and purpose.
CREATE TABLE IF NOT EXISTS email_codes (
    email      TEXT    NOT NULL,
    purpose    TEXT    NOT NULL,
    code_hash  TEXT    NOT NULL,
    created_at TEXT    NOT NULL,
    expires_at TEXT    NOT NULL,
    attempts   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (email, purpose)
);

-- Problem metadata. Difficulty never changes, so this is fetched once per slug.
CREATE TABLE IF NOT EXISTS problems (
    slug       TEXT PRIMARY KEY,
    number     TEXT NOT NULL DEFAULT '',
    title      TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'Unknown',
    -- Topic tags, newest metadata LeetCode gives us. Stored as a plain array.
    tags       TEXT[] NOT NULL DEFAULT '{}'
);

-- What each person solved, one row per problem per day. LeetCode only exposes the
-- last 20 accepted submissions, so this accumulates forwards and cannot be backfilled.
CREATE TABLE IF NOT EXISTS solved_problems (
    user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    slug      TEXT    NOT NULL REFERENCES problems (slug) ON DELETE CASCADE,
    solved_on TEXT    NOT NULL,
    solved_at TEXT    NOT NULL,
    PRIMARY KEY (user_id, slug, solved_on)
);

CREATE INDEX IF NOT EXISTS idx_solved_user_day
    ON solved_problems (user_id, solved_on DESC);

-- Reviewing a problem you solved. A solve becomes due again REVIEW_AFTER_DAYS
-- later; checking it off records a review, and it drops off the list until the
-- next time you solve that problem.
CREATE TABLE IF NOT EXISTS reviews (
    user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    slug        TEXT    NOT NULL REFERENCES problems (slug) ON DELETE CASCADE,
    reviewed_at TEXT    NOT NULL,
    PRIMARY KEY (user_id, slug)
);

CREATE TABLE IF NOT EXISTS sync_state (
    user_id         INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    source          TEXT    NOT NULL,
    last_attempt_at TEXT,
    last_success_at TEXT,
    status          TEXT    NOT NULL DEFAULT 'pending',
    error           TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (user_id, source)
);
"""

MIGRATIONS: list[str] = [
    SCHEMA,
    # Deployed databases predate the group clock.
    "ALTER TABLE groups ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'UTC';",
    # Evening reminders, added and then removed: Render blocks outbound SMTP on
    # free instances, so they could never be delivered. Kept as a no-op so the
    # migration numbering stays stable for databases that already ran it.
    "SELECT 1;",
    # Which problems, not just how many.
    """
    ALTER TABLE users ADD COLUMN IF NOT EXISTS show_problems BOOLEAN NOT NULL DEFAULT true;

    CREATE TABLE IF NOT EXISTS problems (
        slug       TEXT PRIMARY KEY,
        title      TEXT NOT NULL,
        difficulty TEXT NOT NULL DEFAULT 'Unknown'
    );

    CREATE TABLE IF NOT EXISTS solved_problems (
        user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        slug      TEXT    NOT NULL REFERENCES problems (slug) ON DELETE CASCADE,
        solved_on TEXT    NOT NULL,
        solved_at TEXT    NOT NULL,
        PRIMARY KEY (user_id, slug, solved_on)
    );

    CREATE INDEX IF NOT EXISTS idx_solved_user_day
        ON solved_problems (user_id, solved_on DESC);
    """,
    # Problem number and topic tags.
    """
    ALTER TABLE problems ADD COLUMN IF NOT EXISTS number TEXT NOT NULL DEFAULT '';
    ALTER TABLE problems ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';
    """,
    # Reminders are gone; so are their columns.
    """
    ALTER TABLE users DROP COLUMN IF EXISTS nudge_enabled;
    ALTER TABLE users DROP COLUMN IF EXISTS last_nudged_on;
    """,
    # Coming back to a problem a few days later.
    """
    CREATE TABLE IF NOT EXISTS reviews (
        user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        slug        TEXT    NOT NULL REFERENCES problems (slug) ON DELETE CASCADE,
        reviewed_at TEXT    NOT NULL,
        PRIMARY KEY (user_id, slug)
    );
    """,
]

TABLES = (
    "reviews",
    "solved_problems",
    "problems",
    "sync_state",
    "email_codes",
    "identities",
    "daily_activity",
    "memberships",
    "groups",
    "users",
)

_pool: ConnectionPool | None = None
_dsn: str | None = None


def max_connections() -> int:
    return max(2, int(os.environ.get("DB_POOL_MAX", "10")))


def is_local(url: str) -> bool:
    """Whether a DSN points at this machine rather than a hosted database.

    `postgresql:///name` has no host at all, which means a unix socket here.
    Anything naming a real host is treated as remote, and therefore precious.
    """
    from urllib.parse import urlparse

    host = urlparse(normalise_dsn(url)).hostname
    return host in (None, "", "localhost", "127.0.0.1", "::1")


def normalise_dsn(url: str) -> str:
    """Clean up a connection string copied from a provider's dashboard.

    Neon and friends present it as `DATABASE_URL="postgres://..."`, which is shell
    syntax. Pasted whole into a hosting panel, the quotes become part of the value
    and libpq reports `invalid connection option` on a fragment of the URL - an
    error that tells you nothing about the actual mistake.
    """
    url = url.strip()
    for quote in ('"', "'"):
        if len(url) >= 2 and url.startswith(quote) and url.endswith(quote):
            url = url[1:-1].strip()
            break
    if url.startswith("postgres://"):
        return "postgresql://" + url[len("postgres://") :]
    return url


def configure(url: str) -> None:
    """Point the app at a database. Safe to call again; reopens the pool."""
    global _pool, _dsn
    url = normalise_dsn(url)
    if _pool is not None and _dsn == url:
        return
    close()
    _dsn = url
    # Sized so background work can never starve a page request. Neon's free
    # compute allows around a hundred connections, so ten is conservative without
    # being so tight that a group refresh saturates the pool and page loads start
    # timing out - which reads to the person waiting as Internal Server Error.
    _pool = ConnectionPool(
        url,
        min_size=1,
        max_size=max_connections(),
        timeout=15.0,
        # A serverless Postgres closes idle connections when the compute suspends.
        # Recycle ours first, and verify one before handing it out.
        max_idle=180.0,
        check=ConnectionPool.check_connection,
        kwargs={"row_factory": dict_row},
        open=True,
    )
    # The pool runs worker threads; without this, a plain script exit trips
    # PythonFinalizationError trying to join them during interpreter teardown.
    atexit.register(close)


def close() -> None:
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


def _require_pool() -> ConnectionPool:
    if _pool is None:
        raise RuntimeError("db.configure() must be called before use")
    return _pool


@contextmanager
def connection() -> Iterator[psycopg.Connection]:
    """Borrow a connection for reads. Rolls back so nothing leaks into the next user."""
    with _require_pool().connection() as conn:
        try:
            yield conn
        finally:
            conn.rollback()


@contextmanager
def transaction() -> Iterator[psycopg.Connection]:
    """Commits on clean exit, rolls back on exception."""
    with _require_pool().connection() as conn:
        with conn.transaction():
            yield conn


def init_db() -> None:
    with transaction() as conn:
        conn.execute(
            """CREATE TABLE IF NOT EXISTS schema_migrations (
                   version    INTEGER PRIMARY KEY,
                   applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
               )"""
        )
        rows = conn.execute("SELECT version FROM schema_migrations").fetchall()
        applied = {row["version"] for row in rows}
        for index, statements in enumerate(MIGRATIONS):
            if index in applied:
                continue
            conn.execute(statements)
            conn.execute(
                "INSERT INTO schema_migrations (version) VALUES (%s)", (index,)
            )


def reset_all() -> None:
    """Empty every table. For tests only - this is not a migration."""
    with transaction() as conn:
        conn.execute(
            f"TRUNCATE {', '.join(TABLES)} RESTART IDENTITY CASCADE"
        )
